server:
  port: 8083

spring:
  application:
    name: customer-service
  config:
    import: configserver:http://localhost:8087
  cloud:
    config:
      enabled: true
      uri: http://localhost:8087
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/pos_db?createDatabaseIfNotExist=true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/