server:
  port: 8082

spring:
  application:
    name: gateway-service
  config:
    import: configserver:http://localhost:8087
  cloud:
    config:
      enabled: true
      uri: http://localhost:8087
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
          filters:
              name: CircuitBreaker
              args:
                name: customer-service
                fallbackuri: forward:/customerFallBack

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            name: CircuitBreaker
            args:
              name: product-service
              fallbackuri: forward:/productFallBack

        - id: order-service
          uri: lb://order-service
          predicates:
              - Path=/order/**
          filters:
            name: CircuitBreaker
            args:
              name: order-service
              fallbackuri: forward:/orderFallBack

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  endpoint:
    hystrix:
      config:
        hystrix:
          command:
            fallbackcmd:
              execution:
                isolation:
                  thread:
                    timeoutInMilliseconds: 4000


