server:
  port: 8085

spring:
  application:
    name: order-service
  config:
    import: configserver:http://localhost:8087
  cloud:
    config:
      enabled: true
      uri: http://localhost:8087
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/pos_db?createDatabaseIfNotExist=true

