server:
  port: 8087

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sasankaviraj/pos-system-microservices
          clone-on-start: true

